#!/bin/bash
# gen-rules.sh
# Meridian Tier-2/3 rule generator (Gate 5.3 / 5.4)
#
# Renders Meridian's enforced rules into platform-specific *context* files from
# the SINGLE source of truth the hooks already read: .meridian/gates.yaml and
# .meridian/security-rules.yaml. Because every surface is generated from that
# source, the in-editor rules can never silently drift from what the hooks (and
# the git/CI verifier) actually enforce.
#
# These files are the CONTEXT layer — advisory in the editor. The real boundary
# is meridian-verify.sh at commit/CI (G5.2). See docs/platform-tiers.md.
#
# Adapters (one generator core, per-platform output):
#   cursor   -> .cursor/rules/meridian.mdc      (MDC w/ alwaysApply frontmatter)
#   windsurf -> .windsurf/rules/meridian.md
#   cline    -> .clinerules/meridian.md
#   advisory -> MERIDIAN.md                      (Tier 3: Aider/Codex/generic)
#
# Usage:
#   gen-rules.sh [project-dir] [--platform cursor|windsurf|cline|advisory|all] [--stdout]
#   MERIDIAN_PROJECT_DIR=/path gen-rules.sh --platform cursor
#
# Exit codes: 0 = ok, 1 = usage/source error (missing yq or source files)

set -uo pipefail

PROJECT_DIR=""
PLATFORM="all"
STDOUT_ONLY=0

for arg in "$@"; do
    case "$arg" in
        --platform=*) PLATFORM="${arg#*=}" ;;
        --platform)   ;; # value consumed below
        --stdout)     STDOUT_ONLY=1 ;;
        --help|-h)    sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        cursor|windsurf|cline|advisory|all) PLATFORM="$arg" ;;
        -*)           echo "Unknown option: $arg" >&2; exit 1 ;;
        *)            [ -z "$PROJECT_DIR" ] && PROJECT_DIR="$arg" ;;
    esac
done

PROJECT_DIR="${PROJECT_DIR:-${MERIDIAN_PROJECT_DIR:-$(pwd)}}"
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
GATES="$PROJECT_DIR/.meridian/gates.yaml"
RULES="$PROJECT_DIR/.meridian/security-rules.yaml"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

if ! command -v yq >/dev/null 2>&1; then
    echo -e "${RED}✗${NC} yq not found — gen-rules.sh parses YAML and requires it." >&2
    echo "   Install: winget install MikeFarah.yq | choco install yq | brew install yq" >&2
    exit 1
fi
if [ ! -f "$GATES" ]; then
    echo -e "${RED}✗${NC} no .meridian/gates.yaml at $PROJECT_DIR — install a recipe first." >&2
    exit 1
fi

# ─── Renderers (no timestamps → output is deterministic/idempotent) ──────────

render_gates() {
    local n i id label requires artifacts pre
    n=$(yq '.gates | length' "$GATES" 2>/dev/null || echo 0)
    [ "$n" -gt 0 ] || { echo "_(no gates defined)_"; return 0; }
    for (( i=0; i<n; i++ )); do
        id=$(yq -r ".gates[$i].id // \"?\"" "$GATES")
        label=$(yq -r ".gates[$i].label // \"\"" "$GATES")
        requires=$(yq -r "(.gates[$i].requires // []) | join(\", \")" "$GATES")
        artifacts=$(yq -r "(.gates[$i].requires_artifacts // []) | join(\", \")" "$GATES")
        pre=$(yq -r "(.gates[$i].hooks.pre // []) | join(\", \")" "$GATES")
        echo "${i}. **${id}** — ${label}"
        [ -n "$requires" ] && echo "   - depends on: ${requires}"
        [ -n "$artifacts" ] && echo "   - required artifacts: ${artifacts}"
        [ -n "$pre" ] && echo "   - verified by: ${pre}"
    done
}

render_security() {
    local target which="$1" n i sev id msg
    n=$(yq '.rules | length' "$RULES" 2>/dev/null || echo 0)
    [ "$n" -gt 0 ] || { echo "_(no rules)_"; return 0; }
    local any=0
    for (( i=0; i<n; i++ )); do
        sev=$(yq -r ".rules[$i].severity // \"\"" "$RULES")
        [ "$sev" = "$which" ] || continue
        id=$(yq -r ".rules[$i].id // \"?\"" "$RULES")
        msg=$(yq -r ".rules[$i].message // \"\"" "$RULES")
        echo "- **${id}** — ${msg}"
        any=1
    done
    [ "$any" -eq 0 ] && echo "_(none)_"
}

render_body() {
    local project_name
    project_name=$(basename "$PROJECT_DIR")

    cat <<EOF
# Meridian rules — ${project_name}

<!-- GENERATED by scripts/gen-rules.sh from .meridian/gates.yaml and
     .meridian/security-rules.yaml. Do not edit by hand; regenerate after
     changing those sources so this stays in sync with what is enforced. -->

**How enforcement works here.** These rules are advisory *in the editor*. The
real, mechanical boundary is \`scripts/meridian-verify.sh\`, run by a git
pre-commit hook and in CI: a commit that fails verification is rejected on any
platform. Treat the rules below as the contract the commit boundary enforces.

## Gate sequence (do them in order; never skip)

$(render_gates)

A gate's work is not done until its verifier passes. Before committing, run:

    bash scripts/meridian-verify.sh

## Never do this (blocked at the commit/CI boundary)

$(render_security block)

## Avoid (warned)

$(render_security warn)

## Working discipline

- **One feature at a time.** Mark exactly one feature \`in_progress\` in
  \`FEATURES.json\`; finish it before starting another (A001).
- **Never hand-edit \`FEATURES.json\` state or memory files** to claim progress.
  Update only the \`passing\`/lifecycle fields; schema validation will catch
  corruption (A002).
- **Do not self-evaluate a gate.** A separate evaluator writes the verdict; a
  gate stays blocked until it passes (A003).
- **Memory is schema-validated JSONL**, not prose. Let the hooks/verifier
  validate writes.
- **Run \`meridian-verify.sh\` before every commit.** If it fails, fix the cause
  — do not bypass with \`--no-verify\`.
EOF
}

# ─── Adapters ────────────────────────────────────────────────────────────────

write_file() {
    local path="$1" content="$2"
    mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" > "$path"
    echo -e "${GREEN}✓${NC} wrote ${path#$PROJECT_DIR/}"
}

emit_cursor() {
    local body; body="$(render_body)"
    local frontmatter="---
description: Meridian gate + security rules (generated — advisory in-editor, enforced at commit/CI)
globs:
alwaysApply: true
---
"
    write_file "$PROJECT_DIR/.cursor/rules/meridian.mdc" "${frontmatter}${body}"
}

emit_windsurf() { write_file "$PROJECT_DIR/.windsurf/rules/meridian.md" "$(render_body)"; }
emit_cline()    { write_file "$PROJECT_DIR/.clinerules/meridian.md" "$(render_body)"; }
emit_advisory() { write_file "$PROJECT_DIR/MERIDIAN.md" "$(render_body)"; }

# ─── Main ────────────────────────────────────────────────────────────────────

if [ "$STDOUT_ONLY" -eq 1 ]; then
    render_body
    exit 0
fi

case "$PLATFORM" in
    cursor)   emit_cursor ;;
    windsurf) emit_windsurf ;;
    cline)    emit_cline ;;
    advisory) emit_advisory ;;
    all)      emit_cursor; emit_windsurf; emit_cline; emit_advisory ;;
    *) echo "Unknown platform: $PLATFORM (use cursor|windsurf|cline|advisory|all)" >&2; exit 1 ;;
esac
